### ISSUE TITLE
Task 8 (icon box)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#11]
Design a card similar to the "Bordered Featured Boxes" found in the page "featured-boxes.html" of the Canvas theme. 

- The main class for this design is called *s-ibox-col* and define in in a new file at `/styles/_iboxes.scss`
- Define an html file to display it at /tasks/task-008/ibox.html. The html structure should follow this format:

```html
<article class="s-ibox-col">
  <section class="s-ibox-col__icon"><i class="i-some-icon"></i></section>
  <section class="s-ibox-col__content">
    <h1> This is title, big black </h1>
    <p> This is description, grey color </p>
  </section>
</article>
```

**Comment by YusukeYoshihiro** [comment]
Hi Peter, I had tried to push, but an error message appeared. It said `remote: error: GH006: Protected branch update failed for refs/heads/yusuke.` and` ! [remote rejected] yusuke -> yusuke (protected branch hook declined).`
So could you check and change your setting to allow me to push on the repository, please?
