### ISSUE TITLE
Task 15 (admin page schedules)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#13]
We want to design an admin page. The first step is header. We already have the class `s-main-header` for header (in /styles/_headers.scss). The html boilerplate looks like this:

```html
<header class="s-main-header">
				
				<div class="container d-flex align-items-center">
					
					<div class="s-main-header__logo">
						
						<a href="/home">
							
							<img src="/img/logo.png" alt="Billihomes">
							
							
						</a>
						
					</div>
					
					<nav class="s-main-header__left-nav">
						
						<menu class="menu--fill">
							
							<li>
								
								<a class="" href="/our-deal">
									our deal
								</a>
								
							</li>
							
							
							<li>
								
								<a class="" href="/about-us">
									About us
								</a>
								
							</li>
							
							<li>
								
								<a class="" href="/contact-us">
									Contact us
								</a>
								
							</li>
							
						</menu>
						
					</nav>
					
					<nav class="s-main-header__right-nav">
						
						<menu class="">
							
							<li>
								<button class="s-btn s-btn--round s-btn--light">
									Login
								</button>
							</li>
							
							<li>
								<button class="s-btn s-btn--round s-btn--light">
									Signup
								</button>
							</li>
							
						</menu>
						
					</nav>
					
				</div>
				
			</header>
```

The first thing todo is to add a BEM modifier class `s-main-header--dark` which makes the header dark, meaning the background-color should be $primary-color, and the text color should be white. Note that this modifier class is to be applied to the main class, So the html looks like

```html
<header class="s-main-header s-main-header--dark">
 ... header contents as above
</header>
```

Make an html file in your task folder (/tasks/task-015) to test the dark header.

Next, we need to make a sidebar. I like [this sidebar design](https://codepen.io/StephenScaff/pen/bVbEbJ). You just need to design the menu items, no need to worry about the sliding sub-menus. The class name for this sidebar is `s-admin-sidebar` defined in the file `/styles/_admin-bars.scss`. The html boilerplate is:

```html
<menu class="s-admin-sidebar">

 <li>
 <a href="/something"><i class="some-icon"> Appointments </a> 
 </li>

 <li>
 <a href="/something"><i class="some-icon2"> Mortgage rates </a> 
 </li>

 <li>
 <a href="/something"><i class="some-icon3"> Contact forms </a> 
 </li>

</menu>
```

please note that the element `menu` has some styles defined in layer 0 (/bootstrap5/_menu.scss). But these styles are very basic and you can easily overwrite them. Add this sidebar to yout html demo page

**Comment by j-ae** [comment]
Hello, @pmvald

I'm happy to work with you. :)

This is my first time that I use BEM, so I have two questions about BEM.

**1. Organization of CSS with BME**

I looked in the scss files or this project and they have basically this organization.

.block{}
.block__element1{}
.block__element1--modifier1{}
.block__element1--modifier2{}
.block__element2{}
.block__element2--modifier1{}
.block--modifier1{}

So the order is basically based on the name of the css methodology which is BEM.

**However**, why not?

.block{}
.block--modifier1{}
.block__element1{}
.block__element1--modifier1{}
.block__element1--modifier2{}
.block__element2{}
.block__element2--modifier1{}

So I changed the modifer of block to above the elements of the block.
Because, If the block has the long list of elements with modifiers, I think that it is hard to find the modifier of the block.
I know that this is not a big thing but why not?
**What do you think?** 

**2. Html Tag? or Class?**

https://github.com/Appers-lab/billihomes-frontend/blob/6179f68093cd227c0d9fd4957d9565f2ca8a934e/-sass/styles/_headers.scss#L23-L39

This is for the nested html tag css.
But when I read the docs about BEM, I felt that BEM prefers to use class(.class) than Html tag and id(#id) as selectors.

**Should I change above the code to below?**
```
  .menu__link {
    color: $primary-color;
    text-transform: uppercase;
    font-size: 0.9rem;

    &:hover {
      font-size: $font-size-base;
    }

    &.active {
      border-bottom: unset;
      color: $body-color;
      &:hover {
        font-size: 0.9rem;
      }
    }
```

Because this is my first time to use BEM methodology and I'm a person who really like to ask what I really don't get it, 
I may ask you a lot of questions about this project. :) Is it OK for you?

**Comment by pmvald** [comment]
@j-ae 

Answers below:

> Hello, @pmvald
> 
> I'm happy to work with you. :)
> 
> This is my first time that I use BEM, so I have two questions about BEM.
> 
> **1. Organization of CSS with BME**
> 
> I looked in the scss files on this project and they have basically this organization.
> 
> .block{}
> .block__element1{}
> .block__element1--modifier1{}
> .block__element1--modifier2{}
> .block__element2{}
> .block__element2--modifier1{}
> **.block--modifier1{}**
> 
> So the order is basically based on the name of the css methodology which is BEM.
> 
> **However**, why not?
> 
> .block{}
> **.block--modifier1{}**
> .block__element1{}
> .block__element1--modifier1{}
> .block__element1--modifier2{}
> .block__element2{}
> .block__element2--modifier1{}
> 
> So I changed the modifer of block to above the elements of the block.
> Because, If the block has a long list of elements with modifiers, I think that it is hard to find the modifier of the block.
> I know that this is not a big thing but why not?
> **What do you think?**

Order of definitions is up to the programmer. Maybe there are some standards out there for this as well but I'm not aware of them. Most of our blocks are simple (and their elements have no modifier) so the order of styles does not really matter. But yes, maybe it's better to hoist the main block modifier on the top for more visibility. You can use any order you see fit. 



> 
> **2. Html Tag? or Class?**
> 
> https://github.com/Appers-lab/billihomes-frontend/blob/6179f68093cd227c0d9fd4957d9565f2ca8a934e/-sass/styles/_headers.scss#L23-L39
> 
> This is for the nested html tag css.
> But when I read the docs about BEM, I felt that BEM prefers to use class(.class) than Html tag and id(#id) as a selector
> and it trys to avoid the unnecessary nesting.
> 
> **Should I change above the code like below?**
> 
> ```
>   .menu__link {
>     color: $primary-color;
>     text-transform: uppercase;
>     font-size: 0.9rem;
> 
>     &:hover {
>       font-size: $font-size-base;
>     }
> 
>     &.active {
>       border-bottom: unset;
>       color: $body-color;
>       &:hover {
>         font-size: 0.9rem;
>       }
>     }
> ```
> 
> For html,
> 
> ```
>         <nav class="s-main-header__left-nav">
>             <menu class="menu--fill">
>                 <li>
>                     <a class="menu__link" href="/our-deal">
>                         our deal
>                     </a>
>                 </li>
>                 <li>
>                     <a class="menu__link" href="/about-us">
>                         About us
>                     </a>
>                 </li>
>                 <li>
>                     <a class="menu__link" href="/contact-us">
>                         Contact us
>                     </a>
>                 </li>
>             </menu>
>         </nav>
> ```
> 
> Because this is my first time to use BEM methodology and I'm a person who really likes to ask what I don't get it,
> I may ask you a lot of questions during this internship. :) Is it OK with you(But I will always google it first)?

Yes, maybe. We don't fully follow BEM or any other css framework though. We try to get the best of each framework. Note that in general there is no agreement on html/css rules, and each framework has its own set of rules which is sometimes contradictory to the other. For example, while BEM wants us to use class instead of tags, html5 [standards](https://html.spec.whatwg.org/multipage/#toc-semantics) offer different type of tags for specific purposes (`<menu>`, `<dialog>`, `<detail>`, etc) and wants us to use these tags in their place. 

So we try to accommodate both BEM and html5 in our design system: we use BEM for naming, but at the same time we utilize html5 elements where possible. In the example of `<menu>` that you mention, based on html5 standards, `<menu>` has a fixed structure: it contains a number of `<li>` elements, and then each `<li>` contains either a link (`<a>`) or a button (`<button>`). Provided that this is the case, we don't need a class `menu__link` and the standard structure of menu uniquely defines the menu link for us (namely `menu > li > a, menu > li > button`). 

It is also notable that most theme designers and frontend developers do not follow html5 standards, and mainly adhere to BEM or other css frameworks. As a result they use `<div>` for most of the block/elements and style them all with just class. We try to be more html5 friendly. So for the known html5 structures (like menu) we follow the tags instead of classes.
