### ISSUE TITLE
Task 17 (button menu)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#17]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

Design the "Bottom menu" found in the Mobilekit theme at `Components > buttom menu`

Define the class `s-btn-menu` in styles/_menus.m.scss based on the following html biolerplate:

```html
<menu class="s-btn-menu">

<li>
 <button>
  <i class="some icon"></i>
  <p>Today</p>
  </button>
</li>

<li>
 <button>
  <i class="some icon2"></i>
  <p>Calendar</p>
  </button>
</li>

...
</menu>
```

**Comment by pmvald** [comment]
@Chukwudalu Try out this task. Let me know if you have any question.

**Comment by Fodrigoal** [comment]
Hi @pmvald 

I am trying to push my changes to this task but I'm getting the following error:

remote: error: GH006: Protected branch update failed for refs/heads/rodrigo.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To https://github.com/Appers-lab/billihomes-frontend.git
 ! [remote rejected] rodrigo -> rodrigo (protected branch hook declined)
error: failed to push some refs to 'https://github.com/Appers-lab/billihomes-frontend.git'

**Comment by pmvald** [comment]
@Fodrigoal I added permission for you to the branch. Please commit and make a pull request (with the same name as the task) and I'll do review
