### ISSUE TITLE
Task 19 (List views)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#19]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

Components > ListView (listview & divider)

Create a new class `s-listview` in `/styles/_lists.m.scss` based on the following html boilerplate:

```html

<ul class="s-listview">

<section class="s-listview__img">
  <img src="avatar"> or <i class="something> or nothing
</section>

<section class="s-listview__title">
 <p> title </p>
</section>

<menu class="s-listview__menu">
  <li><a href="..."> text or <i class="some-icon"> </a></li>
  <li><button"> text  </button></li>
</menu>

</ul>

```

**Comment by pmvald** [comment]
@akaaariii This task is assigned to you Akari. It belongs to the mobile [pages project](https://github.com/orgs/Appers-lab/projects/3). Please review the guides. Let me know if you have any question.

**Comment by akaaariii** [comment]
@pmvald I got it. I'll let you know if I have any questions. Thank you.
