### ISSUE TITLE
Task 23 (sliding modals/drawers)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#23]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

We want to make web component to create a left and right sliding panels.

To see an example of sliding panel refer to MobileKit theme : `Components > Panel`, and note the sliding panels. 

The panel itself does not need to contain anything. It can be any empty block (div, section, article, etc). Though you will need to determine its width and height, but no need to add header or paragraphs to the panels. The main thing to figure out for now is to write js code to handle the click event which opens up the panels. For now just implement function `openModal`

```html

<body>

<div class="s-drawer">
This is the panel
</div>

<div class="container">
  <button onclick="openModal('left')"> Open left </button>
  <button onclick="openModal('right')"> Open right </button>
</div>

<script>

function openModal(direction) {
   // code here
}

</script>

</body>
```

We mainly wan to do this using css. The js part should manily add/remove classes to the main drawer component (modifires to the s-drawer class) to show/hide it with sliding effect. Please note:

1. Don't worry about the black overlay on the background. We'll add it later. You just slide in/out the drawer
2. No need to lock the body scroll (as done in bootstrap modal class in order to enable scrolling on the drawer). we'll add it later

Once you are done with this we'll make it into a web component.

**Comment by pmvald** [comment]
@YusukeYoshihiro This is a more advanced task for making web components. this is the first step. take a look and see if you have any question. This is part of the [mobile pages project](https://github.com/orgs/Appers-lab/projects/3#card-62745719). Make sure you read the mobile design guide first in `doc/mobile-guide.md` to learn the conventions.

**Comment by YusukeYoshihiro** [comment]
@pmvald
 Hi Peter, I updated `Task 23` for the `Drawer Slide Left and Right panels Part`, please check my code and give me feedback.

Best Regards, 
Yusuke.
