### ISSUE TITLE
Task 25 (sections/ action sheets)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#32]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

In mobilekit go to Components > Action sheet.  We want to make sections similar to what you see on the page. Each section hasa title (the grey area) and content (the white area). 

Define a new class `s-section` in `/styles/_sections.m.scss` based on the following boilerplate:

```html
<section class="s-section">
  <h2> tile - the grey area </h2>
  <div class="s-section__content">
   <!-- any content inside -->
  </div>
</section>
```

Follow the sizes and colors as you see in the theme. For the background-color lets use a variable. Check if `$light-grey` is a good option. Show-case your sections in an html in `/tasks/task-025`.

Next, in the same page on the mobilekit theme, press the *Default* button. See the popup windows that appears on the bottom. We want to design a window similar to that. We just want the window, don't worry about its dark overlay or positioning. Just design the window using the class `s-action-sheet` (in `/styles/_action-sheet.m.scss`) and the following html boilerplate:

```html
<article class="s-action-sheet">
  <h2> Action sheet title <h2>

  <!-- each section is sepearetd from others by lines -->
  <section>
    <menu class="menu-column">
      <li><a> Open </a></li>
      <li><a> Delete </a></li>
     ...
    </menu>
  </section>

  <section>
    <menu class="menu-column">
      <li><a> Close </a></li>
    </menu>
  </section>

</article>
```

Note: we laready define styles for the `<menu>` and the class `menu-column` in `bootstrap5/_menu.scss`. No need to change these classes. Showcase an action sheet in an html file.

**Comment by miyabitanimchi** [comment]
@pmvald 
I have 3 questions regarding this task:

1. For the action sheet, "don't worry about its dark overlay or positioning" is mentioned but does this mean I don't even need to make an animation(popup from bottom to top)? Simply just creating the window itself and show it to an html file?

2. For the sections and the action sheet, do they need to be in the same html file? Or separated file?

3. If they are in the same file/separated files, what name the html file(s) should be? 

I'm sorry if I'm missing information for these question.

**Comment by pmvald** [comment]
@miyabitanimchi 

Answers below:

> @pmvald
> I have 4 questions regarding this task:
> 
> 1. For the action sheet, "don't worry about its dark overlay or positioning" is mentioned but does this mean I don't even need to make an animation(popup from bottom to top)? Simply just creating the window itself and show it to an html file?

Yes! just the window itself. We already have js controller to show modals.


> 2. For the sections and the action sheet, do they need to be in the same html file? Or separated file?

Separate html files (in general each components its its own separate demo html)

> 3. If they are in the same file/separated files, what name the html file(s) should be?

up to you. just make sure they are all in the task folder (in your case `/tasks/task-025`)

> 4. For the unit for font size, padding and margin, should I stick with "rem"?

for font-size we use rem. For margin, padding and basically all "spacing" you can use the variable $spacer. Right now $spacer is set to be 16px. So f you want 8px just say `0.5*$spacer`

> 
> I'm sorry if I'm missing information for these questions.
