### ISSUE TITLE
Task 26 (chips)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#33]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

In mobilekit go to components > chips. We want to design something similar to a chip. Create a new class `s-chip` in `/styles/_chip.scss`, based on the following boilerplate:

```html
<div class="s-chip">
  <!-- this section is optional and may contain icon or image
  <section class="s-chip__image">
    <img> or <i>
  </section>

 <section class="s-chip__title">
   John Doe
 </section>

<!-- this section is optional and it creates a x button-->
 <button class="s-chip__close">
 </button>

</div>
```

**Comment by joergenreyes** [comment]
Hi @pmvald , may I work on this task?

**Comment by pmvald** [comment]
@joergenreyes Sure! And apply the rules I mentioned in my previous comments.
