### ISSUE TITLE
Task 28 (process stepper)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#35]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

In mobilekit go to Components > form wizard. We want to make a stepper like the one on the top of the form (ignore the bottom shadow, we just want the stepper itself).

Create a new class called `s-stepper` in `/styles/_steppers.scss`, and follow this html boilerplate:

```html
<article class="s-stepper">
  <ul>

     <li>
        <label>1</label>
        <p> Check </p>
     <li>

     <li class="active">
        <label>2</label>
        <p> Enter Address </p>
     <li>

     <li>
        <label>3</label>
        <p> Payment </p>
     <li>

     <li>
        <label>4</label>
        <p> Order Done </p>
     <li>

  <ul>
</article>
``` 
Note: the directive class "active" is used to identify the active step.

**Comment by miyabitanimchi** [comment]
@pmvald
Hi, I would like to take this task.

**Comment by miyabitanimchi** [comment]
@pmvald 
Hi Payam, I have one question but for the scss file this time, the name should be _steppers.scss, not _steppers.m.scss? And either way the file should be imported from _style.m.scss?

**Comment by pmvald** [comment]
@miyabitanimchi Yes! We can use this component in desktop pages as well. It's a kind of shared component. So lets define it in steppers.scss and import this file in `_styles.m.scss`
