### ISSUE TITLE
Task 29 (radio/checkbox list)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#38]
(Make sure you have read the mobile design guide found in doc/mobile-guide.md)

We have designed web components `<check-box>` and `<radio-box>` (see task 20 for details). Now we want to extend the class `s-listview` (defined in `/styles/_lists.m.scss`) to make checkbox/radioboxes similar to what you see in Mobilekit Components > checkbox/radio (list example part, however for checkbox keep the box square). Follow this html structure:

```html
<ul class="s-listview">

<li>
  <check-box>checkbox 1</check-box>
</li>

<li>
  <radio-box>radiobox 1</radio-box>
</li>

</ul>
```

**Comment by j-ae** [comment]
@pmvald, there is no radio-box component at task-20.

In addition, is this related with [task-32](https://github.com/Appers-lab/billihomes-frontend/issues/50)?

**Comment by pmvald** [comment]
@j-ae Yes, lets close this task. Task 32 has a more general version of this
