### ISSUE TITLE
Task 7 (footer)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#5]
Find the starter html file for the footer in tasks/task-007/footer.html. We want to style this footer. Note that the fotter consists of two articles:
- the main footer (class ss-footer found in .styles/_footers.scss which is to be implemented)
- The MLS compliance (class ss-mls-cmp found in /project-cmps/_mls.scss)

By editing these classes and also the html layout, style the footer to be more stylish. You may take a look at the dark footer in the *Canvas theme* found in the pages "index.html", "footer-2.html", etc. (refer to the README.md for mor einfo on the canvas theme)

**File expected to change (do not change any other file):** /styles/_footers.scss, /project-cmps/_mls.scss

**Comment by Chukwudalu** [comment]
Are there any specifications you want for the footer?, like the height, background-color and so on @pmvald

**Comment by pmvald** [comment]
@Chukwudalu Details are up to you. We want something simple and typical. As for height, color, etc. there are standards for footer. Youcan refer to the Canvas theme as mentioned in the task description to get idea about these details.

**Comment by Chukwudalu** [comment]
i made a pull request and left some comments, could you please review it. @pmvald
