### ISSUE TITLE
task 35 (html email for verification code)

### ISSUE THREAD

**Issue by pmvald** [Appers-lab/billihomes-frontend#53]
Prerequisite: 
- [design guide](http://appers-lab.com/guides/design-system) 
- [html email guide](http://appers-lab.com/guides/html-email) 

Design an html email template for sending a verification  code to the user. You may use [this template](https://unlayer.com/templates/email-verification) as a starter, and apply the following customization:

- the blue color should be our primary color (you may hard code the color code)
- Replace the envelop icon/image on the top with the text "Billihomes"
- Replace "Verify Your ..." with "Your Confirmation Code"
- the paragraph starting with "Hi ... " and the orange button replaced with "Your verification code is <strong>123</strong>"
- remove the social icons
- in the copyright statement, replace "company" with "billihomes"

Test the email (on gmail or some other) and make sure it looks nice

**Comment by Fodrigoal** [comment]
I will take this task.

 Two questions first:
 1. The paragraph starting with "Hi ... " is supposed to be completely deleted or is it staying?
 2. What should I do with the "Your site.com" image at the top?

**Comment by pmvald** [comment]
@Fodrigoal 

> I will take this task.
cool!
> 
> Two questions first:
> 
> 1. The paragraph starting with "Hi ... " is supposed to be completely deleted or is it staying?
No, that's the main body, we can keep it
> 2. What should I do with the "Your site.com" image at the top?
You can remove it. Just the site name in the blue area should be enough
